#!/usr/bin/env python3
"""
56_typeset.py — set the manuscript as a two-column journal article.

`results/manuscript_final.md` stays the source of truth; this renders it. The geometry is not
invented: it is measured off `resources/papers/Godwin_2023_NSMB_microfibril_cryoEM.pdf`, the
paper in this collection closest to ours (same protein, same journal family), using PyMuPDF —

    page          595.28 x 790.87 pt
    text block    x 39.7 to 563.4, y 46.6 to 745.7
    columns       two, 256.5 pt wide, 9.9 pt gutter
    body          serif, 8.2 pt
    captions      serif, 7.0 pt, opening with a bold "Fig. N | ..." run
    figures       full text width, floated to the top of a page

Fonts: the base-14 Times family, which is what a journal page is set in and which reportlab
embeds without external files. Times covers Latin-1 only, so superscripts and subscripts become
`<super>`/`<sub>` markup, and the handful of Greek letters and arrows are set in an embedded
DejaVu Serif face. The base-14 Symbol font was tried first and is the traditional answer, but it
is not embedded in the output and renders as missing-glyph boxes wherever a viewer lacks it.

Writes: results/FBN1_manuscript_final.pdf, logs/56_typeset_<stamp>.log
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm  # noqa: F401
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (BaseDocTemplate, Frame, FrameBreak, Image as RLImage,
                                NextPageTemplate, PageBreak, PageTemplate, Paragraph, Spacer)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "results" / "manuscript_final.md"
OUT = ROOT / "results" / "FBN1_manuscript_final.pdf"
FIGDIR = ROOT / "figures"

# --- geometry, measured from the reference page -----------------------------------------
PW, PH = 595.28, 790.87
L, R, T, B = 39.7, 31.9, 46.6, 45.2
TEXT_W = PW - L - R                      # 523.7
GUTTER = 9.9
COL_W = (TEXT_W - GUTTER) / 2            # 256.9
TEXT_H = PH - T - B                      # 699.1

INK = HexColor("#101010")
RULE = HexColor("#9a9a9a")
ACCENT = HexColor("#1f5c9e")

# Which figure follows which Results section, and its file. Figures float to the top of the
# page, as they do on the reference pages.
PLACEMENT = [
    ("Variants concentrate at the two features of the module", 1, "fig1_module"),
    ("Cysteine loss destabilises the domain; calcium-ligand loss does not", 2, "fig2_stability"),
    ("The donor rule holds at the Asp and Glu positions and fails at the β-hydroxylation Asn",
     3, "fig3_coordination"),
    ("Neither instrument in routine use sees the difference", 4, "fig4_interpretation"),
]

# Supplementary figures, appended full width at the end. They were never placed in the PDF at
# all -- only the DOCX carried them -- while the text cites Supplementary Fig. S1a-c and S2
# throughout, so the PDF proof was missing two of its six figures.
SUPP_FIGS = [("S1", "figS1_validation"), ("S2", "figS2_structure")]

RUNNING_HEAD = "Article"
FOOTER_LEFT = "Fibrillin-1 calcium-ligand and cysteine variants"

# Front matter, promoted from main() so a caller can set a different draft without editing this
# file. `61_typeset_v3.py` overrides HEADER_RIGHT and STANDFIRST for the citation-free draft.
HEADER_RIGHT = "Preprint — 2 September 2026"
SUBTITLE = "Computational structural analysis — manuscript draft"
STANDFIRST = ("Every value in this paper is regenerated by a script in <font face=\"Courier\" "
              "size=\"6.4\">scripts/</font> and re-derived from "
              "<font face=\"Courier\" size=\"6.4\">data/processed/</font> by an automated "
              "gate; figure sidecars list every printed number.")

# --- Unicode the base-14 Times family cannot encode --------------------------------------
SUP = {"⁰": "0", "¹": "1", "²": "2", "³": "3", "⁴": "4", "⁵": "5", "⁶": "6", "⁷": "7",
       "⁸": "8", "⁹": "9", "⁺": "+", "⁻": "-"}
SUB = {"₀": "0", "₁": "1", "₂": "2", "₃": "3", "₄": "4"}
# Set in the embedded Unicode face rather than mapped onto Symbol's encoding.
UNI = set("ΔαβγδρσμλχΩ≥≤≈→←↔∼±×·°Å")
UNI_FONT = "UniSerif"
UNI_TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"
PLAIN = {"−": "–", "·": "·", "‑": "-"}


def register_fonts() -> None:
    """Times for the page, one embedded Unicode serif for the characters Times cannot encode."""
    if UNI_FONT not in pdfmetrics.getRegisteredFontNames():
        p = Path(UNI_TTF)
        if not p.is_file():
            sys.exit(f"STOP: {UNI_TTF} not found; Greek and arrows would render as boxes")
        pdfmetrics.registerFont(TTFont(UNI_FONT, str(p)))


def esc(t: str) -> str:
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def unicode_fix(t: str) -> str:
    """Superscript/subscript runs to markup; Greek and arrows to the Symbol font."""
    for k, v in PLAIN.items():
        t = t.replace(k, v)
    out, i = [], 0
    while i < len(t):
        ch = t[i]
        if ch in SUP:
            j = i
            while j < len(t) and t[j] in SUP:
                j += 1
            out.append("<super>" + "".join(SUP[c] for c in t[i:j]) + "</super>")
            i = j
        elif ch in SUB:
            j = i
            while j < len(t) and t[j] in SUB:
                j += 1
            out.append("<sub>" + "".join(SUB[c] for c in t[i:j]) + "</sub>")
            i = j
        elif ch in UNI:
            j = i
            while j < len(t) and t[j] in UNI:
                j += 1
            out.append(f'<font face="{UNI_FONT}">{t[i:j]}</font>')
            i = j
        else:
            out.append(ch)
            i += 1
    return "".join(out)


def inline(t: str) -> str:
    """Markdown inline spans to reportlab markup. Order matters: escape, then mark up."""
    t = esc(t)
    t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t)
    t = re.sub(r"(?<!\*)\*([^*\n]+?)\*(?!\*)", r"<i>\1</i>", t)
    t = re.sub(r"`([^`]+?)`", r'<font face="Courier" size="7.2">\1</font>', t)
    return unicode_fix(t)


# --- styles ------------------------------------------------------------------------------
def styles() -> dict:
    """One entry per kind of block. Written out rather than derived from a base style: the
    reference page uses a different size, leading and alignment for almost every one of them."""
    def P_(name, **kw):
        kw.setdefault("fontName", "Times-Roman")
        kw.setdefault("textColor", INK)
        return ParagraphStyle(name, **kw)

    return {
        "title": P_("title", fontName="Helvetica-Bold", fontSize=15.5, leading=18.0,
                    spaceAfter=7),
        "authors": P_("authors", fontSize=8.6, leading=11, spaceAfter=3),
        "affil": P_("affil", fontSize=7.0, leading=8.6, spaceAfter=9,
                    textColor=HexColor("#4a4a4a")),
        "abshead": P_("abshead", fontName="Helvetica-Bold", fontSize=8.4, leading=10,
                      spaceAfter=2),
        "abstract": P_("abstract", fontSize=8.6, leading=11.0, alignment=TA_JUSTIFY,
                       spaceAfter=4),
        "h1": P_("h1", fontName="Helvetica-Bold", fontSize=9.2, leading=11, spaceBefore=9,
                 spaceAfter=2.5),
        "h2": P_("h2", fontName="Helvetica-Bold", fontSize=8.2, leading=10, spaceBefore=7,
                 spaceAfter=1.5),
        "body": P_("body", fontSize=8.2, leading=9.8, alignment=TA_JUSTIFY),
        "body_ind": P_("body_ind", fontSize=8.2, leading=9.8, alignment=TA_JUSTIFY,
                       firstLineIndent=9.5),
        "caption": P_("caption", fontSize=7.0, leading=8.4, alignment=TA_JUSTIFY,
                      spaceBefore=3.5),
        "ref": P_("ref", fontSize=7.0, leading=8.3, alignment=TA_LEFT, leftIndent=9.5,
                  firstLineIndent=-9.5, spaceAfter=1.0),
        "small": P_("small", fontSize=7.0, leading=8.4, alignment=TA_JUSTIFY, spaceAfter=2),
    }


# --- page furniture ----------------------------------------------------------------------
def decorate(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 8.2)
    canvas.setFillColor(INK)
    canvas.drawString(L, PH - 30.5, RUNNING_HEAD)
    canvas.setFont("Times-Roman", 7.4)
    canvas.setFillColor(ACCENT)
    canvas.drawRightString(PW - R, PH - 30.5, HEADER_RIGHT)
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.5)
    canvas.line(L, PH - 36.5, PW - R, PH - 36.5)
    canvas.line(L, B - 8, PW - R, B - 8)
    canvas.setFont("Times-Roman", 7.2)
    canvas.setFillColor(HexColor("#4a4a4a"))
    canvas.drawString(L, B - 17.5, FOOTER_LEFT)
    canvas.setFont("Helvetica-Bold", 8.0)
    canvas.setFillColor(INK)
    canvas.drawRightString(PW - R, B - 17.5, str(canvas.getPageNumber()))
    canvas.restoreState()


def two_col_frames(top: float, height: float):
    return [Frame(L, PH - top - height, COL_W, height, id="c1",
                  leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0),
            Frame(L + COL_W + GUTTER, PH - top - height, COL_W, height, id="c2",
                  leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0)]


def parse(md: str) -> list:
    """Markdown to a flat list of (kind, text) blocks, legends and references split out."""
    text = md.split("\n")
    blocks, buf, section = [], [], None
    def flush():
        nonlocal buf
        if buf:
            blocks.append(("p", " ".join(x.strip() for x in buf).strip()))
            buf = []
    for line in text:
        s = line.rstrip()
        if s.startswith("# "):
            flush(); blocks.append(("title", s[2:].strip())); continue
        if s.startswith("### "):
            flush(); blocks.append(("h2", s[4:].strip())); continue
        if s.startswith("## "):
            flush(); section = s[3:].strip(); blocks.append(("h1", section)); continue
        if s.strip() in ("---", ""):
            flush(); continue
        if re.match(r"^\d+\.\s", s) and section and section.startswith("References"):
            flush(); blocks.append(("ref", s.strip())); continue
        if s.startswith("   ") and blocks and blocks[-1][0] == "ref":
            blocks[-1] = ("ref", blocks[-1][1] + " " + s.strip()); continue
        buf.append(s)
    flush()
    return blocks


def main() -> int:
    if not SRC.is_file():
        sys.exit(f"STOP: {SRC.relative_to(ROOT)} not found")
    register_fonts()
    S = styles()
    blocks = parse(SRC.read_text(encoding="utf-8"))
    log = [f"Typeset — {datetime.now(timezone.utc).isoformat()}",
           f"page {PW:.1f}x{PH:.1f} pt, columns {COL_W:.1f} pt, gutter {GUTTER} pt"]

    # legends, keyed by figure number, pulled out of the legends section
    legends: dict[int, str] = {}
    supp_legends: dict[str, str] = {}
    in_leg = False
    for kind, t in blocks:
        if kind == "h1":
            in_leg = t.startswith("Figure legends")
            continue
        if in_leg and kind == "p":
            m = re.match(r"\*\*(?:Fig\.|Figure) (\d+) \|", t)
            if m:
                legends[int(m.group(1))] = t
            ms = re.match(r"\*\*Supplementary (?:Fig\.|Figure) (S\d+) \|", t)
            if ms:
                supp_legends[ms.group(1)] = t
    log.append(f"{len(legends)} numbered and {len(supp_legends)} supplementary legends found")

    # ---- front matter, full width on page 1
    title = next(t for k, t in blocks if k == "title")
    abstract, seen_abs = [], False
    for k, t in blocks:
        if k == "h1":
            seen_abs = (t == "Abstract")
            continue
        if seen_abs and k == "p":
            abstract.append(t)

    front = [
        Paragraph(inline(title), S["title"]),
        Paragraph(SUBTITLE, S["authors"]),
        Paragraph(STANDFIRST, S["affil"]),
        Paragraph("ABSTRACT", S["abshead"]),
    ] + [Paragraph(inline(p), S["abstract"]) for p in abstract] + [Spacer(1, 5)]

    # wrap() returns the text height only; the style's own spaceBefore/spaceAfter are added by
    # the frame, so they have to be counted here or the last abstract paragraph spills into the
    # first column
    front_h = sum(f.wrap(TEXT_W, TEXT_H)[1] for f in front)
    front_h += sum(getattr(getattr(f, "style", None), "spaceBefore", 0) or 0 for f in front)
    front_h += sum(getattr(getattr(f, "style", None), "spaceAfter", 0) or 0 for f in front)
    front_h += 10
    log.append(f"front matter height {front_h:.0f} pt")

    templates = [
        PageTemplate(id="First", onPage=decorate, frames=[
            Frame(L, PH - T - front_h, TEXT_W, front_h, id="front",
                  leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0),
            *two_col_frames(T + front_h + 6, TEXT_H - front_h - 6)]),
        PageTemplate(id="TwoCol", onPage=decorate, frames=two_col_frames(T, TEXT_H)),
    ]

    # a dedicated template per figure, its top frame sized to that figure
    fig_h = {}
    for _, num, stem in PLACEMENT:
        png = FIGDIR / f"{stem}.png"
        if not png.is_file():
            sys.exit(f"STOP: missing {png.relative_to(ROOT)}")
        w, h = Image.open(png).size
        img_h = TEXT_W * h / w
        cap = Paragraph(inline(legends.get(num, "")), S["caption"])
        cap_h = cap.wrap(TEXT_W, TEXT_H)[1]
        total = img_h + cap_h + 12
        fig_h[num] = (img_h, total)
        templates.append(PageTemplate(id=f"Fig{num}", onPage=decorate, frames=[
            Frame(L, PH - T - total, TEXT_W, total, id=f"f{num}",
                  leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0),
            *two_col_frames(T + total + 8, TEXT_H - total - 8)]))
        log.append(f"  Fig {num} ({stem}) {w}x{h}px -> {img_h:.0f} pt tall, block {total:.0f} pt")

    supp_h = {}
    for tag, stem in SUPP_FIGS:
        png = FIGDIR / f"{stem}.png"
        if not png.is_file():
            sys.exit(f"STOP: missing {png.relative_to(ROOT)}")
        w, h = Image.open(png).size
        img_h = TEXT_W * h / w
        cap = Paragraph(inline(supp_legends.get(tag, "")), S["caption"])
        total = img_h + cap.wrap(TEXT_W, TEXT_H)[1] + 12
        supp_h[tag] = (img_h, total)
        templates.append(PageTemplate(id=f"Fig{tag}", onPage=decorate, frames=[
            Frame(L, PH - T - total, TEXT_W, total, id=f"s{tag}",
                  leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0),
            *two_col_frames(T + total + 8, TEXT_H - total - 8)]))
        log.append(f"  Supp {tag} ({stem}) {w}x{h}px -> {img_h:.0f} pt tall")

    doc = BaseDocTemplate(str(OUT), pagesize=(PW, PH), pageTemplates=templates,
                          leftMargin=L, rightMargin=R, topMargin=T, bottomMargin=B,
                          title=title, author="FBN1 structural analysis",
                          subject="Marfan syndrome; fibrillin-1; cbEGF; calcium coordination")

    story = list(front)
    story.append(FrameBreak())

    fig_after = {sec: (num, stem) for sec, num, stem in PLACEMENT}
    placed: set[int] = set()
    pending: tuple | None = None
    section, in_leg, first_para = None, False, True

    for kind, t in blocks:
        if kind == "title":
            continue
        if kind == "h1":
            section = t
            in_leg = t.startswith("Figure legends")
            if t == "Abstract":
                continue                      # already set full width in the front matter
            if in_leg:
                continue                      # the legends are set as captions under each
                                              # figure, so the heading would stand over nothing
            story.append(Paragraph(inline(t), S["h1"]))
            first_para = True
            continue
        if in_leg:
            continue
        if kind == "h2":
            # flush a figure queued by the previous section before starting a new one
            if pending:
                num, stem = pending
                story += [NextPageTemplate(f"Fig{num}"), PageBreak(),
                          RLImage(str(FIGDIR / f"{stem}.png"), width=TEXT_W,
                                  height=fig_h[num][0]),
                          Paragraph(inline(legends.get(num, "")), S["caption"]),
                          FrameBreak(), NextPageTemplate("TwoCol")]
                placed.add(num)
                pending = None
            story.append(Paragraph(inline(t), S["h2"]))
            first_para = True
            if t in fig_after and fig_after[t][0] not in placed:
                pending = fig_after[t]
            continue
        if kind == "ref":
            story.append(Paragraph(inline(t), S["ref"]))
            continue
        if kind == "p":
            if section in (None, "Abstract"):
                # the abstract is typeset full width above; the untitled preamble under the
                # title is a note to the repository, not part of the paper
                continue
            sty = S["small"] if section in ("Methods", "Data and code availability") else (
                S["body"] if first_para else S["body_ind"])
            story.append(Paragraph(inline(t), sty))
            first_para = False

    if pending:
        num, stem = pending
        story += [NextPageTemplate(f"Fig{num}"), PageBreak(),
                  RLImage(str(FIGDIR / f"{stem}.png"), width=TEXT_W, height=fig_h[num][0]),
                  Paragraph(inline(legends.get(num, "")), S["caption"]),
                  FrameBreak(), NextPageTemplate("TwoCol")]
        placed.add(num)

    for tag, stem in SUPP_FIGS:
        if tag not in supp_legends:
            sys.exit(f"STOP: no legend for supplementary figure {tag}")
        story += [NextPageTemplate(f"Fig{tag}"), PageBreak(),
                  RLImage(str(FIGDIR / f"{stem}.png"), width=TEXT_W, height=supp_h[tag][0]),
                  Paragraph(inline(supp_legends[tag]), S["caption"]),
                  FrameBreak(), NextPageTemplate("TwoCol")]

    missing = [n for _, n, _ in PLACEMENT if n not in placed]
    if missing:
        sys.exit(f"STOP: figures never placed: {missing} — a section heading in PLACEMENT does "
                 "not match the manuscript")

    doc.build(story)
    kb = OUT.stat().st_size / 1024
    log.append(f"wrote {OUT.relative_to(ROOT)} ({kb:.0f} kB), {doc.page} pages")
    print(f"  wrote {OUT.relative_to(ROOT)}  ({kb:.0f} kB, {doc.page} pages)")
    (ROOT / "logs" / f"56_typeset_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.log"
     ).write_text("\n".join(log) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
